name: pip-compile-upgrade

on:
  schedule:
    - cron: '0 13 * * 1'
  workflow_dispatch:

jobs:
  pip-compile-upgrade:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update requirements
        id: pip-compile
        uses: coatl-dev/actions/pip-compile@v2
        with:
          path: requiremens
          python-version: '3.12'

      - name: Detect changes
        id: git-diff
        uses: coatl-dev/actions/simple-git-diff@v2
        with:
          path: requirements

      - name: Import GPG key
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        id: gpg-import
        uses: coatl-dev/actions/gpg-import@v2
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - name: Build commit message
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          echo "chore(requirements): pip-compile upgrade" > "$RUNNER_TEMP/commit.txt"
          {
              echo ""
              echo "updates:"
              git status --porcelain | awk 'match($1, "M") {print "  - " $2}'
          } >> "$RUNNER_TEMP/commit.txt"

      - name: Commit and push changes
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          git checkout -B coatl-dev-pip-compile-upgrade
          git add requirements
          git commit --file="${RUNNER_TEMP}/commit.txt"
          git push --force --set-upstream origin coatl-dev-pip-compile-upgrade

      - name: Create pull request
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        uses: coatl-dev/actions/pr-create@v2
        with:
          gh-token: ${{ secrets.COATL_BOT_GH_TOKEN }}
