name: test

on:
  pull_request:
    branches:
      - coatl
    paths:
      - .github/workflows/test.yml
      - requirements/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: '3.13'

      - name: Dry run pip install
        shell: bash
        working-directory: requirements
        run: |
          for file in *.txt; do
            if [ -f "$file" ]; then
              python -m pip install --dry-run --requirement "$file"
            fi
          done
